# Generated by Django 2.2.5 on 2019-10-31 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Objective',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objective', models.CharField(max_length=1000)),
                ('mission', models.CharField(max_length=1000)),
                ('vision', models.CharField(max_length=1000)),
            ],
        ),
    ]
